#!/usr/bin/env python3
"""Regenerate emoji.tsv from a Unicode emoji-test.txt file.

Usage:
    python3 tools/build_emoji_data.py [path-or-url]

Defaults to the Emoji 16.0 data file, which is the newest set Apple Color Emoji
ships glyphs for (macOS 15.4 and later). Skin tone variants are dropped: they
multiply the list by five and are noise for a one-glyph label.

Output columns: emoji, group, subgroup, name.
"""

import re
import sys
import urllib.request
from pathlib import Path

DEFAULT_SOURCE = "https://unicode.org/Public/emoji/16.0/emoji-test.txt"
SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}
OUT = Path(__file__).resolve().parent.parent / "emoji.tsv"

LINE = re.compile(
    r"^(?P<codes>[0-9A-F ]+?)\s*;\s*(?P<status>[a-z-]+)\s*#\s*\S+\s+E\d+\.\d+\s+(?P<name>.+)$"
)


def read_source(source: str) -> str:
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as response:
            return response.read().decode("utf-8")
    return Path(source).read_text(encoding="utf-8")


def build(text: str) -> list[tuple[str, str, str, str]]:
    rows = []
    group = subgroup = ""
    for line in text.splitlines():
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
            continue
        if line.startswith("# subgroup:"):
            subgroup = line.split(":", 1)[1].strip()
            continue
        if not line or line.startswith("#"):
            continue

        match = LINE.match(line)
        if not match or match.group("status") != "fully-qualified":
            continue

        codepoints = [int(code, 16) for code in match.group("codes").split()]
        if any(code in SKIN_TONES for code in codepoints):
            continue

        rows.append(
            (
                "".join(chr(code) for code in codepoints),
                group,
                subgroup,
                match.group("name").strip(),
            )
        )
    return rows


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    rows = build(read_source(source))
    if not rows:
        print("no emoji parsed, refusing to overwrite emoji.tsv", file=sys.stderr)
        return 1

    with OUT.open("w", encoding="utf-8") as handle:
        handle.write("# generated by tools/build_emoji_data.py from %s\n" % source)
        for row in rows:
            handle.write("\t".join(row) + "\n")

    print(f"wrote {len(rows)} emoji to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
